#' @title tmatrix_psd: Checks the positive semidefinite property of a sequence
#'
#' @description Generates a toeplitz matrix with the given sequence as its first row and checks it it is not positive semidefinite. Sequences must be at least of length 2.
#'
#' @usage tmatrix_psd(n = 100, s)
#'
#' @param n numeric, the maximum dimensions of the toeplitz matrix to check.
#' @param s numeric vector, the sequence which forms the first row of the toeplitz matrix.
#
#' @details After checking the initial matrix generated by s, the function creates a new sequence by adding 0 to the existing one. It repeats till the dimensions of the matrix generated is n by n.
#'
#' @return Returns the dimensions of the matrix at which the sequence is found to be not positive semidefinite. If it cannot determine for the given n, returns -1.
#' @export
#'
#' @author Aaron Khoo
#'
#' @examples
#' tmatrix_psd(100, c(1, 0, -0.4, -0.2))
#' tmatrix_psd(2, c(6, 3))
tmatrix_psd <- function(n = 100, s) {

  if (n < length(s) || length(s) == 0 || length(s) == 1) {
    return (NULL)
  }

  temp_s = s
  for (i in 0:(n-length(s))){
    e_values = eigen(toeplitz(temp_s))$values
    check = e_values < 0

    if ("TRUE" %in% check) {
      return(length(temp_s))
    }

    temp_s <- c(temp_s, 0)
  }

  return(-1)

}




#' @title convert_complex_exp: Convert a complex number from polar to exponential form
#'
#' @description Converts a complex number from polar to exponential form.
#'
#' @usage convert_complex_exp(z)
#'
#' @param z A complex type object as defined by R.
#'
#' @return Returns a vector containing the magnitude of z and the angle in radians corresponding to its expenential form.
#' @export
#'
#' @author Aaron Khoo
#'
#' @examples
#' convert_complex_exp(2-2i)
#' convert_complex_exp(-3+4i)
convert_complex_exp <- function(z) {

  if (is.complex(z) == FALSE){
    return (NULL)
  }

  r = Mod(z)
  x = atan(Im(z)/Re(z))

  return (c(r, x))

}




#' @title spec_density: Spectral density values
#'
#' @description Calculates the spectral density of a sequence for a given range of frequencies assuming it is the autocovariance function (acvf) of a weakly stationary process.
#'
#' @usage spec_density(s, lowerBound = -0.5, upperBound = 0.5, step = 0.1)
#'
#' @param s numeric vector, first row of toeplitz matrix.
#' @param lowerBound double, lower bound of frequency range.
#' @param upperBound double, upper bound of frequency range.
#' @param step double, increment for loop.
#'
#' @return Returns a numeric vector containing the values of the spectral distribution at each frequency index.
#' @export
#'
#' @author Aaron Khoo
#'
#' @examples
#' spec_density(s=c(1.25, 0.5), lowerBound=-0.5, upperBound=0.5)
#' spec_density(s=c(2, 1, 0.5, -0.2), lowerBound=-0.5, upperBound=0.5)
spec_density <- function(s, lowerBound = -0.5, upperBound = 0.5, step = 0.1) {

  freq <- seq(from=lowerBound, to=upperBound, by=step)
  y <- numeric(length(freq))

  i = 1
  for (w in freq) {
    y[i] = Re(spec_density_w(s, w))
    i = i + 1
  }

  return (y)

}




#' @title spec_density_plot: Spectral density plot
#'
#' @description Plots values of the spectral density of a sequence for a given frequency range.
#'
#' @usage spec_density_plot(s, lowerBound = -0.5, upperBound = 0.5, step = 0.1)
#'
#' @param s numeric vector, first row of toeplitz matrix.
#' @param lowerBound double, lower bound of frequency range.
#' @param upperBound double, upper bound of frequency range.
#' @param step double, increment for loop.
#'
#' @return Returns the spectral density plot.
#' @export
#'
#' @author Aaron Khoo
#'
#' @examples
#' spec_density_plot(s=c(1.25, 0.5), lowerBound=-0.5, upperBound=0.5)
#' spec_density_plot(s=c(1, 0, 0.5, -0.2), lowerBound=-0.5, upperBound=0.5)
spec_density_plot <- function(s, lowerBound = -0.5, upperBound = 0.5, step = 0.1) {

  freq <- seq(from=lowerBound, to=upperBound, by=step)
  y <- numeric(length(freq))

  i = 1
  for (w in freq) {
    y[i] = Re(spec_density_w(s, w))
    i = i + 1
  }

  return (plot(y=y, x=freq, type="l", main="Spectral Distribution", xlab="Frequencies", ylab="Value"))

}




#' @title spec_density_w: Helper function
#'
#' @description Calculates the spectral density value for a given frequency.
#'
#' @usage spec_density_w(s, w)
#'
#' @param s numeric sequence, first row of toeplitz matrix.
#' @param w double, frequency.
#'
#' @return Returns value of spectral density at the given frequency.
#'
#' @author Aaron Khoo
spec_density_w <- function(s, w) {

  y = numeric(length(s))
  y[1] = s[1]

  if (length(s) > 1) {
    for (h in 1:(length(s)-1)) {
      y[h+1] = s[h+1]*(cos(-2*pi*w*h) + (0+1i)*(sin(-2*pi*w*h)) + cos(2*pi*w*h) + (0+1i)*(sin(2*pi*w*h)))
    }
  }

  return (sum(y))

}



